# Project information
site_name: "AIB001's Homepage"
site_url: https://aib001.github.io/
site_author: "A.I.B."
site_description: "Personal academic website and research portfolio"

# Repository
repo_name: AIB001/aib001.github.io
repo_url: https://github.com/AIB001/aib001.github.io
edit_uri: ""

# Copyright
copyright: "Copyright &copy; 2025 A.I.B."

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.path
    - toc.integrate
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - header.autohide
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    logo: material/atom-variant
    repo: fontawesome/brands/github

# Custom CSS
extra_css:
  - stylesheets/extra.css

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/AIB001
    - icon: fontawesome/brands/twitter
      link: https://X.com
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/zhaoqi-shi-9800a6345/

# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - footnotes
  - tables
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

# JavaScript for MathJax
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Plugins
plugins:
  - search
  - tags

# Page tree with nested structure
nav:
  - "": index.md    # The entrance page - not visible in navigation
  - Home: home.md   # The main homepage (renamed from original index.md)
  - Academic Research:
      - research/index.md
      - Small Molecules:
          - LigTraj: research/small-molecules/LigTraj_Software_Database.md
          - CDK7 Inhibitor Design: research/small-molecules/CDK7.md
      - Condensates:
          - Droplet Formation Dynamics: research/condensates/FUS_PLD_Droplet.md
          - CGAnalysis: research/condensates/cganalysis.md
      - Other Research:
          - THZ1 Nano Drug Delivery: research/others/collaborative.md
      - Tools and Tutorial: 
          - GROMACS Tutorial: research/tools/GROMACS_protocol.md
          - NAMD Tutorial: research/tools/NAMD_CDK7example.md
          - NAMD Parametering new residue: research/tools/NAMD_Parametering_new_residue.md
          - Picture Style: research/tools/picture_style.md
      - Publications: research/publications.md
  - Learning:
      - learning/index.md
      - Biology:
          - Neuron Science1: learning/biology/neuron_science1.md
          - Neuron Science2: learning/biology/neuron_science2.md
          - Ecology1: learning/biology/ecology1.md
          - Ecology2: learning/biology/ecology2.md
      - Physics:
          - Computational Physics: learning/physics/Computational_Physics_forZJU.md
          - Equilibrium Statistical Physics: learning/physics/Equilibrium_Statistical_Physics.md
          - Field Theory: learning/physics/field_theory.md
      - Computational Biophysics & Others:
          - Free Energy Pertubation: learning/others/Principle_of_FEP.md
  - Life:
      - life/index.md